# Copyright 2010-2023 by Sebastian Thomschke and contributors.
# SPDX-License-Identifier: EPL-2.0
#
# Author: Sebastian Thomschke, https://sebthom.de/
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.adoc'
    - '**/*.md'
    - '.github/*.yml'
  pull_request:
  workflow_dispatch:
    # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
    inputs:
      additional_maven_args:
        description: 'Additional Maven Args'
        required: false
        default: ''

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency: ci-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 11
          may_create_release: ${{ github.ref == 'refs/heads/main' }}
          experimental: false
        - java: 17
          may_create_release: false
          experimental: false
        - java: 19
          may_create_release: false
          experimental: false

    steps:
    - name: "ACT: Install ping"
      if: runner.os == 'Linux' && env.ACT # https://github.com/nektos/act#skipping-steps
      run: |
        if ! hash ping 2>/dev/null; then
          apt-get update
          apt-get -y install iputils-ping
        fi

    - name: Show environment variables
      run: env | sort

    - name: Git Checkout
      uses: actions/checkout@v3 #https://github.com/actions/checkout

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3 #https://github.com/actions/setup-java
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    # reusing CDS archives of the same JVM randomly fails in GitHub Actions with
    # "An error has occurred while processing the shared archive file. shared class paths mismatch"
    #- name: Calculate Java version checksum
    #  id: java-version-checksum
    #  run: |
    #    echo "md5sum=$(java -version 2>&1 | md5sum | cut -f1 -d" ")" >> $GITHUB_OUTPUT
    #- name: Cache Java CDS archive
    #  uses: actions/cache@v3
    #  with:
    #    path: |
    #      ~/.xshare/${{ steps.java-version-checksum.outputs.md5sum }}
    #    key: ${{ runner.os }}-xshare-${{ steps.java-version-checksum.outputs.md5sum }}

    - name: "Cache: Restore"
      id: cache-restore
      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.m2/bin
          ~/.m2/repository
          !~/.m2/repository/net/sf/jstuff
        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

    - name: Test with Maven
      id: maven-test
      if: ${{ !matrix.may_create_release || env.ACT }}
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_API_KEY: ${{ github.token }}
        JAVA_VERSION: ${{ matrix.java }}
        MAY_CREATE_RELEASE: false
      run: |
        bash .ci/build.sh ${{ github.event.inputs.additional_maven_args }}

    - name: Build with Maven
      id: maven-build
      if: ${{ matrix.may_create_release && !env.ACT }}
      env:
        DEPLOY_SNAPSHOTS_TO_GITHUB_BRANCH: true
        GITHUB_USER: ${{ github.actor }}
        GITHUB_API_KEY: ${{ secrets.GH_API_TOKEN }}
        JAVA_VERSION: ${{ matrix.java }}
        MAY_CREATE_RELEASE: true
        SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
        SIGN_KEY_PASS: ${{ secrets.GPG_SIGN_KEY_PWD }}
        SONATYPE_OSSRH_USER: ${{ secrets.SONATYPE_OSSRH_USER }}
        SONATYPE_OSSRH_USER_TOKEN: ${{ secrets.SONATYPE_OSSRH_USER_TOKEN }}
      run: |
        set -eu

        # https://github.community/t/github-actions-bot-email-address/17204
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        bash .ci/build.sh ${{ github.event.inputs.additional_maven_args }}

        if find . -path "*/target/site/jacoco/jacoco.xml" | grep -q .; then
          echo 'has_jacoco_results=true' >> $GITHUB_OUTPUT
        fi

    - name: Publish test coverage to codeclimate.com
      uses: paambaati/codeclimate-action@v3.2.0 # https://github.com/paambaati/codeclimate-action
      if: ${{ matrix.may_create_release && steps.maven-build.outputs.has_jacoco_results && !env.ACT }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
        JACOCO_SOURCE_PATH: "${{ github.workspace }}/jstuff-core/src/main/java ${{ github.workspace }}/jstuff-integration/src/main/java ${{ github.workspace }}/jstuff-xml/src/main/java"
      with:
        coverageLocations:  |
          ${{ github.workspace }}/jstuff-core/target/site/jacoco/jacoco.xml:jacoco
          ${{ github.workspace }}/jstuff-core/target/site/jacoco-it/jacoco.xml:jacoco
          ${{ github.workspace }}/jstuff-integration/target/site/jacoco/jacoco.xml:jacoco
          ${{ github.workspace }}/jstuff-integration/target/site/jacoco-it/jacoco.xml:jacoco
          ${{ github.workspace }}/jstuff-xml/target/site/jacoco/jacoco.xml:jacoco
          ${{ github.workspace }}/jstuff-xml/target/site/jacoco-it/jacoco.xml:jacoco


    ##################################################
    # Cache Update
    # See https://github.com/actions/cache/issues/342
    ##################################################
    - name: "Cache: Delete Previous"
      if: ${{ steps.cache-restore.outputs.cache-hit && !env.ACT }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh extension install actions/gh-actions-cache
        gh actions-cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} --confirm

    - name: "Cache: Update"
      uses: actions/cache/save@v3
      if: ${{ always() && !env.ACT }} # save cache even fails
      with:
        path: |
          ~/.m2/bin
          ~/.m2/repository
          !~/.m2/repository/net/sf/jstuff
        key: ${{ steps.cache-restore.outputs.cache-primary-key }}


  ###########################################################
  cleanup:
  ###########################################################
    runs-on: ubuntu-latest
    needs: 
      - build

    steps:
    - name: "Delete intermediate build artifacts"
      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
      uses: geekyeggo/delete-artifact@v2 # https://github.com/GeekyEggo/delete-artifact/
      with:
        name: "*"
        failOnError: false
