# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: Stale issues

on:
  schedule:
    - cron: '0 16 * * 1'
  workflow_dispatch:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4  # https://github.com/actions/checkout
      - name: Run stale action
        uses: ./.github/actions/stale@v1
